engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
    config:
      extensions:
      - .json
      - .js
  fixme:
    enabled: true
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false
exclude_paths:
- ".*"
ratings:
  paths:
  - "**.json"
