engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
    config:
      extensions:
      - .json
      - .js
    exclude_paths:
    - "**/*"
    - "!keys.json"
  fixme:
    enabled: true
exclude_paths:
- "spec/"
- ".*"
ratings:
  paths:
  - "**.json"
