engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
    config:
      extensions:
      - .json
      - .js
  fixme:
    enabled: true
exclude_paths:
- "**/**"
- "!spec/"
ratings:
  paths:
  - "**.json"
